const FETCH_USERS = 'FETCH_USERS'
const FETCH_POSTS = 'FETCH_POSTS'
const FETCH_POSTS_USER = 'FETCH_POSTS_USER'
const FETCH_USER_ID = 'FETCH_USER_ID'
const FETCH_USER = 'FETCH_USER'
const FETCH_COMMENTS = 'FETCH_COMMENTS'

export {
  FETCH_USERS,
  FETCH_POSTS,
  FETCH_POSTS_USER,
  FETCH_USER_ID,
  FETCH_USER,
  FETCH_COMMENTS,
}
