const APP_LOADING_START = 'APP_LOADING_START'
const APP_LOADING_END = 'APP_LOADING_END'
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
const FETCH_SELECTED_USER_ID_SUCCESS = 'FETCH_SELECTED_USER_ID_SUCCESS'
const FETCH_SELECTED_USER = 'FETCH_SELECTED_USER'
const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
const FETCH_POSTS_BY_USER_SUCCESS = 'FETCH_POSTS_BY_USER_SUCCESS'
const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'

export {
  APP_LOADING_START,
  APP_LOADING_END,
  FETCH_USERS_SUCCESS,
  FETCH_POSTS_BY_USER_SUCCESS,
  FETCH_SELECTED_USER_ID_SUCCESS,
  FETCH_POSTS_SUCCESS,
  FETCH_SELECTED_USER,
  FETCH_COMMENTS_SUCCESS,
}
